### PR TITLE
Require blocks on newline

### PR DESCRIPTION
**Pull request by brittanydionigi**
Any other rules anybody cares to add? https://github.com/jscs-dev/node-jscs#rules

### CODE REVIEW

**Comment by tofumatt** [comment]
Looks good to me... I added a few extra, including 4 lines for indents... it's usually what I've seen at Moz. Does that run afoul of node conventions? I tend to spend more time coding JS for browsers where four spaces are definitely the norm.

**Comment by brittanydionigi** [comment]
Ahh, I was going to add indentation as well - because that's one that I am always sloppy about. But we have a couple instances where we might want to be able to bypass the indentation rule - i.e. https://github.com/mozilla/recroom/blob/master/recroom.js#L75 Cool with whatever you wanna do in that scenario.

**Comment by brittanydionigi** [comment]
Also, lololololol at the epic invalidity of the dino banner
screen shot 2014-10-02 at 7 29 35 pm

**Comment by tofumatt** [comment]
## Dino is trolling! 

tofumatt (Sent from mobile)

**Comment by brittanydionigi** [comment]
Also thoughts on adding these grunt tasks as a pre-commit hook? I'm often the type to forget to run grunt :santa:

**Comment by tofumatt** [comment]
It should be running them as part of the tests, so Travis will complain that the "build is failing" if the tests fail. https://github.com/mozilla/recroom/blob/master/Gruntfile.js#L43

**Comment by tofumatt** [comment]
Regarding indentation, I assume the linter will be smart enough to allow indents like your example... otherwise maybe we shouldn't use it? The Python checkers I'm used to always made exceptions wisely. Maybe the JSCS does too?

Or we could mark them off manually, but that sounds tedious.

**Comment by brittanydionigi** [comment]
Yep my B, I thought it was complaining about that particular line when I first ran it with indentation rules. It was complaining about a more legitimate indentation faux-pas.  Let's give the indentation rules a try and if it winds up trolling us we can take it out later.

Travis is passing on this branch now - feel free to merge.

**Comment by tofumatt** [comment]
Cool, done! :+1:

**Comment by tofumatt** [comment]
Heh, and it errored. https://travis-ci.org/mozilla/recroom/jobs/37057374

I’ll clean it up in a few minutes ^_^

**Comment by brittanydionigi** [comment]
Hah whoops, yea previous PR that got merged just before this was under less rules. Should've remembered to rebase off that but the green merge button is just ... so...inviting... CANT HELP IT.

**Pull request merged**
